language: node_js
node_js:
  - node

cache: npm

install:
  - yarn install


script:
  - yarn test
  - yarn test build


deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: travis